---
title: "PCS1 simulation continuous binomial"
output: html_document
date: "2024-02-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- function(pr,pt,fi)
{
  1+(fi-1)*(pr+pt)
}

b <- function(pr,pt,fi) 
{
  -4*fi*(fi-1)*pr*pt
}

##p11,p12,p21,p22
prob <- function(pr,pt,fi)
{
  if(fi==1)
  {
    p<-c(pr*pt,pr-pr*pt,pt-pr*pt,1-pr-pt+pr*pt)
    p
  }
  else{
  a<- 1+(fi-1)*(pr+pt)
  b <- -4*fi*(fi-1)*pr*pt
  p <- matrix(nrow = 2, ncol = 2)
  p[1,1] <- round(( a - ( a^2+b )^(0.5) ) / (2*(fi-1)),digits = 4)
  p[1,2] <- round(pr-p[1,1],digits = 4)
  p[2,1] <- round(pt-p[1,1],digits = 4)
  p[2,2] <- round(1 - p[1,1] - p[1,2] - p[2,1],digits = 4)
  p <- c(p[1,1],p[1,2],p[2,1],p[2,2])
  p}
}
```

```{r}
n1<-5
n2<-16  
r1<- 1
r2<- 3
t1<- 1
t2<- 3

p_e0<-0.5
p_s0<-0.5
delta_e2<-0.2
delta_s2<-0.2
delta_e1<-0.05
delta_s1<-0.05



    p_e<- c(p_e0,p_e0+delta_e1, p_e0+delta_e1)
    p_s<- c(p_s0,p_s0+delta_s1, p_s0+delta_s1)
    
    k<- length(p_e) -1
    phi <- 2

    p<- matrix(data=NA,nrow = k+1,ncol=4)

    for(i in 1: (k+1))
    { 
      p [i,] <- prob(p_e[i],p_s[i],phi)
    }
    
    
    
```

```{r}
p_e0<-0.7
p_s0<-0.6
delta_e2 <- 0.1
delta_s2 <- 0.1

ee<-seq(0,1,length.out=30)
ss<-seq(0,1,length.out=30)




n1<-10
n2<-10
r1<-1
r2<-2
t1<-1
t2<-2
N<-10000
x0<-rmultinom(N,n1,p[1,])
x<-matrix(data = NA,nrow = k, ncol = N)

x1<-rmultinom(N,n1,p[2,])
x2<-rmultinom(N,n1,p[3,])

u0<-runif(N,0,0.5)
u1<-runif(N,0,0.5)
u2<-runif(N,0,0.5)

s<-0
ss<-0
for(i in 1:N)
{
  
  if( (x2[1,i]+x2[2,i]-(x0[1,i]+x0[2,i]))>=r1 & (x2[1,i]+x2[3,i]-(x0[1,i]+x0[3,i]))>=t1)
  {
    if((x1[1,i]+x1[2,i]-(x0[1,i]+x0[2,i]))>=r1 & (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i]))>=t1 & (x2[1,i]+x2[2,i]-(x1[1,i]+x1[2,i]))> 0)
    {
      s<-s+1
    }
    else if((x1[1,i]+x1[2,i]-(x0[1,i]+x0[2,i]))>=r1 & (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i]))>=t1 & (x2[1,i]+x2[2,i]-(x1[1,i]+x1[2,i]))==0)
    {
      s<-s+1/k
    }
    else if((x1[1,i]+x1[2,i]-(x0[1,i]+x0[2,i]))<r1 | (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i]))<t1)
    {
      s<-s+1
    }
  }
  
  
  
  
    if( (x2[1,i]+x2[2,i]-(x0[1,i]+x0[2,i]))>=r1 & (x2[1,i]+x2[3,i]-(x0[1,i]+x0[3,i]))>=t1)
  {
    if((x1[1,i]+x1[2,i]-(x0[1,i]+x0[2,i]))>=r1 & (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i]))>=t1 & (x2[1,i]+x2[2,i]+u2[i]-(x1[1,i]+x1[2,i]+u1[i]))> 0)
    {
      ss<-ss+1
    }
    
    else if((x1[1,i]+x1[2,i]-(x0[1,i]+x0[2,i]))<r1 | (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i]))<t1)
    {
      ss<-ss+1
    }
  }

}
result<-s/N
result2<-ss/N    
 
result
result2
 

```

