---
title: "PCS0 exact functions"
output: html_document
date: "2023-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- function(pr,pt,fi)
{
  1+(fi-1)*(pr+pt)
}

b <- function(pr,pt,fi) 
{
  -4*fi*(fi-1)*pr*pt
}

##p11,p12,p21,p22
prob <- function(pr,pt,fi)
{
  if(fi==1)
  {
    p<-c(pr*pt,pr-pr*pt,pt-pr*pt,1-pr-pt+pr*pt)
    p
  }
  else{
  a<- 1+(fi-1)*(pr+pt)
  b <- -4*fi*(fi-1)*pr*pt
  p <- matrix(nrow = 2, ncol = 2)
  p[1,1] <- round(( a - ( a^2+b )^(0.5) ) / (2*(fi-1)),digits = 4)
  p[1,2] <- round(pr-p[1,1],digits = 4)
  p[2,1] <- round(pt-p[1,1],digits = 4)
  p[2,2] <- round(1 - p[1,1] - p[1,2] - p[2,1],digits = 4)
  p <- c(p[1,1],p[1,2],p[2,1],p[2,2])
  p}
}
```



```{r}
n1<-5
n2<-16  
r1<- 1
r2<- 3
t1<- 1
t2<- 3

p_e0<-0.5
p_s0<-0.5
delta_e2<-0.2
delta_s2<-0.2
delta_e1<-0.05
delta_s1<-0.05



    p_e<- c(p_e0,p_e0+delta_e1, p_e0+delta_e1)
    p_s<- c(p_s0,p_s0+delta_s1, p_s0+delta_s1)
    
    k<- length(p_e) -1
    phi <- 2

    p00 <- matrix(data=NA,nrow = k+1,ncol=4)

    for(i in 1: (k+1))
    { 
      p00[i,] <- prob(p_e[i],p_s[i],phi)
    }
    
    
    


```



$P(Xr=xr,Xt=xt)$
```{r}
#P(Xr=xr,Xt=xt)
joint_prob <- function(xr,xt,n1,p)
{
  sum <- 0
  for(i in max(0,xr+xt-n1) : min(xr,xt))
  {
    if(i<0 || xr-i<0 || xt-i<0 || n1-xr-xt+i<0)
    {
      sum<-sum+0
    }
    else{
    x <- c( i , xr-i , xt-i , n1-xr-xt+i )
    sum <- sum + dmultinom(x, size = NULL, prob = p, log = FALSE)
    ##cat("s = ", sum,"x =", x, "\n")
    }
  }
  sum
}
```









$P(X_e^{11}-X_e^{10}<e_1,X_s^{11}-X_s^{10}<s_1, X_e^{12}-X_e^{10}<e_1,X_s^{12}-X_s^{10}<s_1)$
```{r}
pcs01<-function(e1,e2,s1,s2,n1,n2,p0,p1,p2)
{
  s<-0
  for(a in 0:min(n1,n1+e1-1))
  {
    for(b in 0:min(n1,n1+s1-1))
    {
      for(c in 0:min(n1+e1-1,n1))
      {
        for(d in 0:min(n1,n1+s1-1))
        {
          for(e in max(a-e1+1,c-e1+1,0):n1)
          {
            for(f in max(b-s1+1,d-s1+1,0):n1)
            {
              s<-s+ joint_prob(a,b,n1,p1) * joint_prob(c,d,n1,p2) * joint_prob(e,f,n1,p0)
            }
          }
        }
      }
    }
  }
  s
}
```


test
```{r}
NN<-100
result0<-seq(0,0,length=NN)

for(j in  1:NN)
{
s<-0
N<-10000

x0<-rmultinom(N,n1,p00[1,])
# x<-matrix(data = NA,nrow = k, ncol = N)
x1<-rmultinom(N,n1,p00[2,])
x2<-rmultinom(N,n1,p00[3,])

xx0<-rmultinom(N,n2,p00[1,])
#x<-matrix(data = NA,nrow = k, ncol = N)
xx1<-rmultinom(N,n2,p00[2,])
xx2<-rmultinom(N,n2,p00[3,])


for( i in 1:N)
{
  if(    (  (x2[1,i]+x2[2,i]-(x0[1,i]+x0[2,i]))<r1 & (x2[1,i]+x2[3,i]-(x0[1,i]+x0[3,i]))<t1  )     &    (  (x1[1,i]+x1[2,i]-(x0[1,i]+x0[2,i]))<r1 & (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i]))<t1  )  )
  {
    s<-s+1
  }
  

result0[j]<-s/N
}}

summary(result0)

pcs01(r1,r2,t1,t2,n1,n2,p00[1,],p00[2,],p00[3,])
```

PCS010 $P(X_e^{12}-X_e^{10}\ge e_1,X_s^{12}-X_s^{10}\ge s_1,X_s^{11}-X_s^{10}< s_1)$
```{r}
pcs010<-function(e1,e2,s1,s2,n1,n2,p0,p1,p2)
{
  s<-0
  for (a in 0:n1) 
    {
       for(b in 0:min(n1,n1+s1-1))
       {
         for(c in max(e1,0):min(n1+e1,n1))
         {
           for(d in max(s1,b+1):min(n1,n1+s1))
           {
             for(e in 0:min(c-e1,n1))
             {
               for(f in max(b-s1+1,0):min(n1,d-s1))
               {
                 s<-s+joint_prob(a,b,n1,p1) * joint_prob(c,d,n1,p2) * joint_prob(e,f,n1,p0)
               }
             }
           }
         }
       }
    
    
  }
  s
}


pcs011<-function(e1,e2,s1,s2,n1,n2,p0,p1,p2)
{
  s<-0
  for(a in 0:(n1-1))
  {
    for(b in max(s1,0):min(n1+s1,n1))
    {
      for(c in max(e1,a+1):min(n1+e1,n1))
      {
        for(d in max(s1,0):min(n1+s1,n1))
        {
          for(e in 0:min(c-e1,n1))
          {
            for(f in 0:min(b-s1,d-s1,n1))
            {
              s<-s+joint_prob(a,b,n1,p1) * joint_prob(c,d,n1,p2) * joint_prob(e,f,n1,p0)
            }
          }
        }
      }
    }
  }
  s
}

pcs012<-function(e1,e2,s1,s2,n1,n2,p0,p1,p2)
{
  s<-0
  for(b in max(s1,0):min(n1+s1,n1))
  {
    for(c in max(e1,0):min(n1+e1,n1))
    {
      for(d in max(s1,0):min(n1+s1,n1))
      {
        for(e in 0:min(c-e1,n1))
        {
          for(f in 0:min(b-s1,d-s1,n1))
          {
            s<-s+joint_prob(c,b,n1,p1) * joint_prob(c,d,n1,p2) * joint_prob(e,f,n1,p0)
          }
        }
      }
    }
  }
  s/2
}
```


test $\pi_2$ to stage 2 (PCS010+PCS011+PCS012)
```{r}


NN<-100
result0<-seq(0,0,length=NN)

for(j in  1:NN)
{
s<-0
N<-10000

x0<-rmultinom(N,n1,p00[1,])
# x<-matrix(data = NA,nrow = k, ncol = N)
x1<-rmultinom(N,n1,p00[2,])
x2<-rmultinom(N,n1,p00[3,])

xx0<-rmultinom(N,n2,p00[1,])
#x<-matrix(data = NA,nrow = k, ncol = N)
xx1<-rmultinom(N,n2,p00[2,])
xx2<-rmultinom(N,n2,p00[3,])


for( i in 1:N)
{
  if( (x2[1,i]+x2[2,i]-(x0[1,i]+x0[2,i]))>=r1 & (x2[1,i]+x2[3,i]-(x0[1,i]+x0[3,i]))>=t1 )
  {
    if( (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i])) < t1 )
    {
      s<-s+1
    }
    
  }

result0[j]<-s/N
}}

summary(result0)


NN<-100
result0<-seq(0,0,length=NN)

for(j in  1:NN)
{
s<-0
N<-10000

x0<-rmultinom(N,n1,p00[1,])
# x<-matrix(data = NA,nrow = k, ncol = N)
x1<-rmultinom(N,n1,p00[2,])
x2<-rmultinom(N,n1,p00[3,])

xx0<-rmultinom(N,n2,p00[1,])
#x<-matrix(data = NA,nrow = k, ncol = N)
xx1<-rmultinom(N,n2,p00[2,])
xx2<-rmultinom(N,n2,p00[3,])


for( i in 1:N)
{
  if( (x2[1,i]+x2[2,i]-(x0[1,i]+x0[2,i]))>=r1 & (x2[1,i]+x2[3,i]-(x0[1,i]+x0[3,i]))>=t1 )
  {
    
    if( (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i])) >= t1  &  x2[1,i]+x2[2,i]> x1[1,i]+x1[2,i])
    {
      s<-s+1
    }
  
  }

result0[j]<-s/N
}}

summary(result0)


NN<-100
result0<-seq(0,0,length=NN)

for(j in  1:NN)
{
s<-0
N<-10000

x0<-rmultinom(N,n1,p00[1,])
# x<-matrix(data = NA,nrow = k, ncol = N)
x1<-rmultinom(N,n1,p00[2,])
x2<-rmultinom(N,n1,p00[3,])

xx0<-rmultinom(N,n2,p00[1,])
#x<-matrix(data = NA,nrow = k, ncol = N)
xx1<-rmultinom(N,n2,p00[2,])
xx2<-rmultinom(N,n2,p00[3,])


for( i in 1:N)
{
  if( (x2[1,i]+x2[2,i]-(x0[1,i]+x0[2,i]))>=r1 & (x2[1,i]+x2[3,i]-(x0[1,i]+x0[3,i]))>=t1 )
  {
    if( (x1[1,i]+x1[3,i]-(x0[1,i]+x0[3,i])) >= t1  &  x2[1,i]+x2[2,i]== x1[1,i]+x1[2,i])
    {
      s<-s+1/2
    }
  }

result0[j]<-s/N
}}

summary(result0)


pcs010(r1,r2,t1,t2,n1,n2,p00[1,],p00[2,],p00[3,])
pcs011(r1,r2,t1,t2,n1,n2,p00[1,],p00[2,],p00[3,])
pcs012(r1,r2,t1,t2,n1,n2,p00[1,],p00[2,],p00[3,])
```



